import type { CampaignItem, CampaignStats } from './types';

export const INITIAL_CAMPAIGNS: CampaignItem[] = [
  {
    id: 'camp-01',
    title: 'Summer Glow 2026',
    brandName: 'Lumina Cosmetics',
    brandAvatarInitials: 'LC',
    brandAvatarBg: 'bg-[#7C3AED]', // Tím violet
    platforms: ['TikTok', 'Instagram'],
    budgetFormatted: '320M đ',
    budgetRaw: 320000000,
    disbursedAmount: '198M đ',
    disbursedPercent: 62,
    kocCurrent: 14,
    kocTarget: 20,
    deadline: '15/08/2026',
    daysRemaining: 19,
    progress: 62,
    status: 'active',
    category: 'Làm đẹp',
    createdAt: '02/07/2026',
    productName: 'Serum dưỡng ẩm Hydra X',
    productType: 'Sản phẩm',
    description:
      'Chiến dịch quảng bá dòng serum dưỡng ẩm mùa hè, tập trung vào nhóm KOC lĩnh vực làm đẹp với nội dung review chân thực và hướng dẫn sử dụng.',
    targetAudience: 'Nữ từ 18 - 30 tuổi, yêu thích làm đẹp và skincare.',
    minFollowers: '500K người theo dõi',
    submittedAt: '10/06/2026',
    kocRequirements: {
      minFollowers: '500K người theo dõi',
      contentType: 'Video review + Story',
      niche: 'Làm đẹp, Đời sống',
      demographics: 'Toàn quốc · 18 – 30',
    },
    deliverables: [
      {
        type: '1 video TikTok ≥ 60 giây',
        count: 1,
        description: 'Review chất serum, độ thẩm thấu và hiệu quả căng mọng.',
      },
      {
        type: '3 ảnh feed Instagram',
        count: 3,
        description: 'Bộ ảnh chất lượng cao kèm caption trải nghiệm thực tế.',
      },
      {
        type: '2 story gắn link mua hàng',
        count: 2,
        description: 'Story kèm sticker link UTM khuyến mãi độc quyền.',
      },
    ],
    kocStats: {
      registered: 14,
      approved: 3,
      submitted: 3,
    },
    results: {
      reach: '4.2M',
      impressions: '18.6M',
      engagementRate: '7.8%',
      conversionRate: '3.2%',
    },
    registeredKocs: [
      {
        id: 'koc-1',
        name: 'Mai Anh',
        handle: '@maianh.beauty',
        initials: 'MA',
        avatarBg: 'bg-[#8B5CF6]',
        platforms: ['TikTok', 'Instagram'],
        status: 'Đã duyệt',
      },
      {
        id: 'koc-2',
        name: 'Hải Yến',
        handle: '@yenlifestyle',
        initials: 'HY',
        avatarBg: 'bg-[#EC4899]',
        platforms: ['TikTok', 'YouTube'],
        status: 'Đã nộp bài',
      },
      {
        id: 'koc-3',
        name: 'Bảo Trân',
        handle: '@tran.fashion',
        initials: 'BT',
        avatarBg: 'bg-[#14B8A6]',
        platforms: ['Instagram', 'TikTok'],
        status: 'Chờ duyệt',
      },
      {
        id: 'koc-4',
        name: 'Minh Quân',
        handle: '@quantech',
        initials: 'MQ',
        avatarBg: 'bg-[#F97316]',
        platforms: ['YouTube'],
        status: 'Đã duyệt',
      },
      {
        id: 'koc-5',
        name: 'Tuấn Kiệt',
        handle: '@kietkgaming',
        initials: 'TK',
        avatarBg: 'bg-[#3B82F6]',
        platforms: ['YouTube', 'TikTok'],
        status: 'Đã nộp bài',
      },
    ],
  },
  {
    id: 'camp-02',
    title: 'Ra mắt Serum X',
    brandName: 'Lumina Cosmetics',
    brandAvatarInitials: 'LC',
    brandAvatarBg: 'bg-[#F43F5E]', // Đỏ hồng
    platforms: ['TikTok', 'YouTube'],
    budgetFormatted: '150M đ',
    budgetRaw: 150000000,
    kocCurrent: 0,
    kocTarget: 15,
    deadline: '30/08/2026',
    daysRemaining: 34,
    progress: 0,
    status: 'pending',
    category: 'Chăm sóc da đặc trị',
    description:
      'Ra mắt tinh chất phục hồi da chuyên sâu Serum X công nghệ mới. Cần tìm các Creator uy tín có kiến thức về thành phần mỹ phẩm (Niacinamide, B5, Ceramide).',
    targetAudience: 'Nam và Nữ từ 20 - 35 tuổi quan tâm đến phục hồi màng da.',
    minFollowers: '25.000+ followers',
    submittedAt: '12/07/2026',
    deliverables: [
      {
        type: 'TikTok Video 45s-60s',
        count: 1,
        description: 'Chia sẻ hành trình dùng 7 ngày với hình ảnh trước/sau.',
      },
      {
        type: 'YouTube Short',
        count: 1,
        description: 'Short phân tích bảng thành phần và lý do chọn sản phẩm.',
      },
    ],
  },
  {
    id: 'camp-03',
    title: 'Nova Buds ra mắt',
    brandName: 'NovaTech',
    brandAvatarInitials: 'N',
    brandAvatarBg: 'bg-[#06B6D4]', // Xanh ngọc
    platforms: ['YouTube', 'TikTok'],
    budgetFormatted: '900M đ',
    budgetRaw: 900000000,
    kocCurrent: 9,
    kocTarget: 12,
    deadline: '05/09/2026',
    daysRemaining: 40,
    progress: 48,
    status: 'active',
    category: 'Công nghệ & Phụ kiện',
    description:
      'Trải nghiệm tai nghe chống ồn chủ động Nova Buds Pro với chất âm Hi-Res và thời lượng pin 36 tiếng. Ưu tiên Creator mảng công nghệ, âm nhạc hoặc lifestyle.',
    targetAudience: 'Giới trẻ, dân văn phòng, người yêu thích công nghệ & du lịch.',
    minFollowers: '100.000+ followers',
    submittedAt: '25/06/2026',
    deliverables: [
      {
        type: 'YouTube Video Review chi tiết (3-5p)',
        count: 1,
        description: 'Đánh giá tính năng chống ồn, độ trễ gaming và chất âm.',
      },
      {
        type: 'TikTok Hands-on 30s',
        count: 1,
        description: 'Cảm nhận nhanh thiết kế và khả năng vừa vặn khi vận động.',
      },
    ],
  },
  {
    id: 'camp-04',
    title: 'Món ngon mùa hè',
    brandName: 'FreshBite',
    brandAvatarInitials: 'F',
    brandAvatarBg: 'bg-[#F59E0B]', // Cam vàng
    platforms: ['Instagram', 'TikTok'],
    budgetFormatted: '220M đ',
    budgetRaw: 220000000,
    kocCurrent: 0,
    kocTarget: 18,
    deadline: '25/08/2026',
    daysRemaining: 29,
    progress: 0,
    status: 'pending',
    category: 'Ẩm thực & Nhà hàng',
    description:
      'Menu giải nhiệt mùa hè 2026 với các món smoothie bowl, trà trái cây và salad tươi hữu cơ. KOC đến trực tiếp cửa hàng trải nghiệm hoặc nhận combo giao tận nhà.',
    targetAudience: 'Food reviewers, học sinh, sinh viên và dân văn phòng.',
    minFollowers: '15.000+ followers',
    submittedAt: '13/07/2026',
    deliverables: [
      {
        type: 'TikTok Mukbang / Check-in',
        count: 1,
        description: 'Video trải nghiệm không gian quán và thưởng thức món mới.',
      },
      {
        type: 'Instagram Post carousel',
        count: 1,
        description: 'Bộ ảnh 5 ảnh chất lượng cao kèm địa chỉ quán.',
      },
    ],
  },
  {
    id: 'camp-05',
    title: 'Săn sale Back-to-School',
    brandName: 'Anker Vietnam',
    brandAvatarInitials: 'A',
    brandAvatarBg: 'bg-[#2563EB]', // Xanh dương
    platforms: ['TikTok', 'YouTube'],
    budgetFormatted: '450M đ',
    budgetRaw: 450000000,
    kocCurrent: 25,
    kocTarget: 25,
    deadline: '10/08/2026',
    daysRemaining: -2,
    progress: 95,
    status: 'overdue',
    category: 'Phụ kiện công nghệ',
    description:
      'Combo củ sạc nhanh GaN và cáp dù siêu bền dành cho sinh viên mùa tựu trường. Chiến dịch đã kết thúc thời hạn nhưng còn một số KOC chưa nộp báo cáo.',
    targetAudience: 'Học sinh, sinh viên mùa tựu trường 2026.',
    minFollowers: '30.000+ followers',
    submittedAt: '01/06/2026',
    deliverables: [
      {
        type: 'TikTok Săn Deal',
        count: 1,
        description: 'Gắn link giỏ hàng TikTok Shop kèm voucher độc quyền.',
      },
    ],
  },
  {
    id: 'camp-06',
    title: 'Bộ sưu tập Thu Đông 2026',
    brandName: 'Routine Fashion',
    brandAvatarInitials: 'R',
    brandAvatarBg: 'bg-[#4F46E5]', // Tím than Indigo
    platforms: ['TikTok', 'Instagram'],
    budgetFormatted: '280M đ',
    budgetRaw: 280000000,
    kocCurrent: 8,
    kocTarget: 15,
    deadline: '20/09/2026',
    daysRemaining: 55,
    progress: 30,
    status: 'paused',
    category: 'Thời trang & May mặc',
    description:
      'Giới thiệu lookbook Thu Đông phong cách tối giản Minimalism. Thương hiệu đang tạm dừng nhận đơn để điều chỉnh lại danh mục sản phẩm gửi KOC.',
    targetAudience: 'Nam và Nữ yêu thích phong cách thời trang thanh lịch.',
    minFollowers: '40.000+ followers',
    submittedAt: '05/07/2026',
    deliverables: [
      {
        type: 'TikTok Phối đồ Lookbook',
        count: 1,
        description: '3 gợi ý outfit phong cách Smart Casual.',
      },
    ],
  },
  {
    id: 'camp-07',
    title: 'Khai trương Chi nhánh Q.1',
    brandName: 'Highlands Coffee',
    brandAvatarInitials: 'HL',
    brandAvatarBg: 'bg-[#DC2626]', // Đỏ tươi
    platforms: ['TikTok'],
    budgetFormatted: '180M đ',
    budgetRaw: 180000000,
    kocCurrent: 12,
    kocTarget: 12,
    deadline: '01/08/2026',
    daysRemaining: -11,
    progress: 100,
    status: 'completed',
    category: 'Chuỗi F&B',
    description:
      'Chiến dịch check-in chi nhánh mới với không gian mở hiện đại. Toàn bộ 12 KOC đã hoàn thành chỉ tiêu đăng bài và đạt vượt 125% KPI lượt xem.',
    targetAudience: 'Khách hàng khu vực TP.HCM.',
    minFollowers: '20.000+ followers',
    submittedAt: '15/05/2026',
    deliverables: [
      {
        type: 'TikTok Check-in',
        count: 1,
        description: 'Review đồ uống signature và không gian check-in mới.',
      },
    ],
  },
  {
    id: 'camp-08',
    title: 'Nước tăng lực Spark X',
    brandName: 'Spark Beverage',
    brandAvatarInitials: 'SB',
    brandAvatarBg: 'bg-[#CA8A04]', // Vàng đậm
    platforms: ['TikTok'],
    budgetFormatted: '100M đ',
    budgetRaw: 100000000,
    kocCurrent: 0,
    kocTarget: 10,
    deadline: '12/08/2026',
    daysRemaining: 0,
    progress: 0,
    status: 'rejected',
    category: 'Đồ uống & Nước giải khát',
    description:
      'Chiến dịch bị từ chối do nhãn hàng chưa bổ sung đầy đủ giấy công bố an toàn thực phẩm theo quy định kiểm duyệt của sàn.',
    targetAudience: 'Người chơi thể thao, game thủ.',
    minFollowers: '10.000+ followers',
    submittedAt: '02/07/2026',
    deliverables: [
      {
        type: 'TikTok Video',
        count: 1,
        description: 'Trải nghiệm hương vị mới khi tập gym.',
      },
    ],
  },
];

export function computeStats(campaigns: CampaignItem[]): CampaignStats {
  return {
    total: campaigns.length,
    pending: campaigns.filter((c) => c.status === 'pending').length,
    active: campaigns.filter((c) => c.status === 'active').length,
    overdue: campaigns.filter((c) => c.status === 'overdue').length,
  };
}
