import type { KocItem } from './types';

export const MOCK_KOCS: KocItem[] = [
  {
    id: 'koc-01',
    name: 'Mai Anh',
    handle: '@maianh.beauty',
    initials: 'MA',
    avatarGradient: 'from-[#7C5CFF] to-[#A78BFA]',
    followers: [
      { platform: 'TikTok', count: '800K' },
      { platform: 'Instagram', count: '400K' },
    ],
    engagement: [
      { platform: 'TikTok', rate: '9.2%' },
      { platform: 'Instagram', rate: '6.8%' },
    ],
    category: 'Làm đẹp',
    campaigns: 12,
    revenue: '340M',
    status: 'active',
    email: 'maianh.beauty@gmail.com',
    phone: '0901 234 567',
    // Dữ liệu mẫu đối chiếu bố cục ảnh tham chiếu, không phải API thật.
    platformMetrics: [
      { platform: 'TikTok', averageViews: '180K', totalLikes: '2.4M' },
      { platform: 'Instagram', averageViews: '60K', averageLikes: '12K' },
    ],
    brandReviews: {
      averageRating: 4.5,
      contentQuality: 4.5,
      timeliness: 4.5,
      professionalism: 4.5,
      reviews: [
        {
          id: 'review-01',
          brand: 'Lumina Cosmetics',
          campaign: 'Summer Glow 2026',
          date: '12/07/2026',
          rating: 5,
          comment: 'Nội dung sáng tạo, đúng deadline, rất chuyên nghiệp.',
        },
        {
          id: 'review-02',
          brand: 'GreenLife',
          campaign: 'Sống xanh mỗi ngày',
          date: '05/04/2026',
          rating: 4,
          comment: 'Hợp tác tốt, nội dung ổn, giao tiếp dễ chịu.',
        },
      ],
    },
    campaignHistory: [
      {
        id: 'history-01',
        campaign: 'Summer Glow 2026',
        brand: 'Lumina Cosmetics',
        period: '06/2026 – 07/2026',
        revenue: '86M',
        status: 'active',
      },
      {
        id: 'history-02',
        campaign: 'Ra mắt Serum X',
        brand: 'Lumina Cosmetics',
        period: '04/2026',
        revenue: '62M',
        status: 'active',
      },
      {
        id: 'history-03',
        campaign: 'Chiến dịch Tết',
        brand: 'FreshBite',
        period: '01/2026',
        revenue: '104M',
        status: 'suspended',
      },
      {
        id: 'history-04',
        campaign: 'Back to School',
        brand: 'UrbanWear',
        period: '08/2025',
        revenue: '48M',
        status: 'pending',
      },
    ],
  },
  {
    id: 'koc-02',
    name: 'Hải Yến',
    handle: '@yenlifestyle',
    initials: 'HY',
    avatarGradient: 'from-[#EF4623] to-[#F49E4C]',
    followers: [
      { platform: 'TikTok', count: '1.3M' },
      { platform: 'YouTube', count: '800K' },
    ],
    engagement: [
      { platform: 'TikTok', rate: '7.1%' },
      { platform: 'YouTube', rate: '4.2%' },
    ],
    category: 'Đời sống',
    campaigns: 15,
    revenue: '512M',
    status: 'suspended',
    email: 'yenlifestyle@gmail.com',
    phone: '0912 345 678',
  },
  {
    id: 'koc-03',
    name: 'Bảo Trân',
    handle: '@tran.fashion',
    initials: 'BT',
    avatarGradient: 'from-[#14B8A6] to-[#5EEAD4]',
    followers: [
      { platform: 'Instagram', count: '580K' },
      { platform: 'TikTok', count: '400K' },
    ],
    engagement: [
      { platform: 'Instagram', rate: '7.6%' },
      { platform: 'TikTok', rate: '6.4%' },
    ],
    category: 'Thời trang',
    campaigns: 11,
    revenue: '300M',
    status: 'active',
    email: 'tran.fashion@gmail.com',
    phone: '0923 456 789',
  },
  {
    id: 'koc-04',
    name: 'Minh Quân',
    handle: '@quantech',
    initials: 'MQ',
    avatarGradient: 'from-[#F59E0B] to-[#FCD34D]',
    followers: [{ platform: 'YouTube', count: '720K' }],
    engagement: [{ platform: 'YouTube', rate: '6.8%' }],
    category: 'Công nghệ',
    campaigns: 9,
    revenue: '240M',
    status: 'active',
    email: 'quantech.review@gmail.com',
    phone: '0934 567 890',
  },
  {
    id: 'koc-05',
    name: 'Tuấn Kiệt',
    handle: '@kiethgaming',
    initials: 'TK',
    avatarGradient: 'from-[#3B82F6] to-[#93C5FD]',
    followers: [
      { platform: 'YouTube', count: '560K' },
      { platform: 'TikTok', count: '330K' },
    ],
    engagement: [
      { platform: 'YouTube', rate: '5.3%' },
      { platform: 'TikTok', rate: '7.6%' },
    ],
    category: 'Game',
    campaigns: 8,
    revenue: '210M',
    status: 'active',
    email: 'kiethgaming@gmail.com',
    phone: '0945 678 901',
  },
  {
    id: 'koc-06',
    name: 'Đức Huy',
    handle: '@huyfit',
    initials: 'ĐH',
    avatarGradient: 'from-[#EC4899] to-[#F9A8D4]',
    followers: [{ platform: 'Instagram', count: '430K' }],
    engagement: [{ platform: 'Instagram', rate: '7.7%' }],
    category: 'Thể hình',
    campaigns: 6,
    revenue: '128M',
    status: 'active',
    email: 'huyfit.coach@gmail.com',
    phone: '0956 789 012',
  },
  {
    id: 'koc-07',
    name: 'Linh Chi',
    handle: '@linhchi.food',
    initials: 'LC',
    avatarGradient: 'from-[#10B981] to-[#6EE7B7]',
    followers: [
      { platform: 'Instagram', count: '310K' },
      { platform: 'TikTok', count: '250K' },
    ],
    engagement: [
      { platform: 'Instagram', rate: '8.1%' },
      { platform: 'TikTok', rate: '10.9%' },
    ],
    category: 'Ẩm thực',
    campaigns: 4,
    revenue: '96M',
    status: 'pending',
    email: 'linhchi.food@gmail.com',
    phone: '0967 890 123',
  },
  {
    id: 'koc-08',
    name: 'Gia Bảo',
    handle: '@giabao.travel',
    initials: 'GB',
    avatarGradient: 'from-[#F97316] to-[#FDBA74]',
    followers: [
      { platform: 'TikTok', count: '260K' },
      { platform: 'Facebook', count: '90K' },
    ],
    engagement: [
      { platform: 'TikTok', rate: '11.5%' },
      { platform: 'Facebook', rate: '4.9%' },
    ],
    category: 'Du lịch',
    campaigns: 3,
    revenue: '72M',
    status: 'pending',
    email: 'giabao.travel@gmail.com',
    phone: '0978 901 234',
  },
];
